version: '3.1'
services:

  db:
    build:
      context: ./database
    container_name: users_db
    image: userdb
    restart: always
    ports:
      - 3311:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql

  api:
    build:
      context: ./api
    container_name: users_api
    image: userapi
    restart: always
    depends_on: 
      - db
    ports:
       - 8888:8888

volumes:
  db_data:

#docker-compose pull
#docker-compose up -d
#docker-compose -f stackdb.yml pull
#docker-compose -f stackdb.yml up -d